const fallback=[{slug:'real-estate-creative',title:'Real Estate Creative',category:'Featured Case Study',description:'Campaign, social media, print, photography and video production.',image_url:'',size:'big',gradient:'gradient-1'},{slug:'lamborghini-poster',title:'Lamborghini Poster',category:'Graphic Design',description:'High-impact automotive poster composition and visual direction.',image_url:'',size:'med',gradient:'gradient-1'},{slug:'golden-hour-studies',title:'Golden Hour Studies',category:'Photography',description:'Atmospheric photography focused on silhouette and warm light.',image_url:'',size:'small',gradient:'gradient-3'},{slug:'product-poster-design',title:'Product & Poster Design',category:'Graphic Design',description:'Selected product visuals, posters and branding explorations.',image_url:'',size:'small',gradient:'gradient-1'}];
const menuBtn=document.getElementById('menuBtn');const mobileMenu=document.getElementById('mobileMenu');menuBtn?.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});mobileMenu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('open');menuBtn?.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function initCursor(){if(!matchMedia('(hover:hover) and (pointer:fine)').matches||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const c=document.createElement('div');c.className='cursor active';c.textContent='VIEW';document.body.appendChild(c);let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY},{passive:true});function loop(){x+=(tx-x)*.18;y+=(ty-y)*.18;c.style.left=x+'px';c.style.top=y+'px';requestAnimationFrame(loop)}loop();document.addEventListener('mouseover',e=>{const t=e.target.closest('[data-cursor]');if(t){c.textContent=t.dataset.cursor||'VIEW';c.style.opacity='1'}else c.style.opacity='.65'})}initCursor();
function initSoftwareLogos(){const logos=[
['https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/photoshop/photoshop-original.svg','Ps'],
['https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/illustrator/illustrator-plain.svg','Ai'],
['https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/premierepro/premierepro-original.svg','Pr'],
['https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/aftereffects/aftereffects-original.svg','Ae'],
['https://cdn.simpleicons.org/adobelightroomclassic/31A8FF','Lr'],
['https://cdn.simpleicons.org/canva/00C4CC','Ca']
];document.querySelectorAll('.software-card img').forEach((img,i)=>{const cfg=logos[i];if(!cfg)return;img.src=cfg[0];img.onerror=()=>{const badge=document.createElement('span');badge.className='software-logo-fallback';badge.textContent=cfg[1];img.replaceWith(badge)}})}initSoftwareLogos();
function cardMarkup(p,i){const size=['big','med','small','small'][i]||'small';const visual=p.image_url?`<div class="visual"><img src="${p.image_url}" alt="${p.title}" loading="lazy" onerror="this.parentElement.classList.add('gradient-1');this.remove()"></div>`:`<div class="visual ${p.gradient||'gradient-1'}"><div class="ghost">${p.title}</div></div>`;return `<a class="card ${size}" data-cursor="OPEN" href="project.html?project=${encodeURIComponent(p.slug||p.id||i+1)}">${visual}<div class="meta"><div class="kicker">${p.category||'Project'}</div><div class="meta-head"><h3>${p.title}</h3><span class="arrow">↗</span></div><p>${p.description||''}</p></div></a>`}
async function loadProjects(){let items=fallback;try{const r=await fetch('./projects.json',{cache:'no-store'});if(r.ok){const d=await r.json();if(Array.isArray(d)&&d.length)items=d}}catch{}const wanted=['real-estate-creative','lamborghini-poster','product-poster-design','golden-hour-studies'];const curated=wanted.map(slug=>items.find(p=>p.slug===slug)).filter(Boolean);const grid=document.getElementById('work-grid');if(!grid)return;grid.innerHTML=curated.map(cardMarkup).join('')}loadProjects();