const params=new URLSearchParams(location.search);let active=params.get('category')||'all';let sub=params.get('sub')||'all';
const categories={
'all':{title:'All Works',intro:'รวมผลงานทั้งหมดที่คัดและเชื่อมเข้าระบบแล้ว สามารถกรองตามสายงานหลักได้'},
'real-estate':{title:'Real Estate',intro:'งานอสังหาริมทรัพย์ แยกเป็น Photography, Print Media, Promotional Design, Social Media Design และ Video Production',subs:['all','photography','print-media','promotional-design','social-media-design','video-production']},
'graphic-design':{title:'Graphic Design',intro:'Poster, Product Visual, Branding Concept และ Promotional Artwork'},
'motion-2d':{title:'Motion Graphics 2D',intro:'รวมโปรเจกต์ Motion 2D ทั้งหมด พร้อมเข้าไปดู Video Player และรายละเอียดแต่ละงาน'},
'photography':{title:'Photography',intro:'ผลงานภาพถ่ายส่วนตัว แยกเป็น Cosplay, Golden Hour / Warm Tone, Landscape และ Macro Photography',subs:['all','cosplay','golden-hour','landscape','macro-photography']}
};
const mainOrder=['all','real-estate','graphic-design','motion-2d','photography'];
const labels={'all':'All','real-estate':'Real Estate','graphic-design':'Graphic Design','motion-2d':'Motion 2D','photography':'Photography','cosplay':'Cosplay','golden-hour':'Golden Hour / Warm Tone','landscape':'Landscape','macro-photography':'Macro Photography','print-media':'Print Media','promotional-design':'Promotional Design','social-media-design':'Social Media Design','video-production':'Video Production'};
function keyFor(p){if(p.category_key)return p.category_key;if(p.category==='Motion Graphics 2D')return'motion-2d';if(p.category==='Photography')return'photography';if(p.category==='Graphic Design')return'graphic-design';if((p.slug||'').includes('real-estate')||p.category==='Featured Case Study')return'real-estate';return'other'}
function subKeyFor(p){if(p.subcategory)return p.subcategory;if(keyFor(p)==='photography'&&p.slug==='golden-hour-studies')return'golden-hour';return'all'}
function updateURL(){const u=new URL(location.href);if(active==='all')u.searchParams.delete('category');else u.searchParams.set('category',active);if(sub==='all')u.searchParams.delete('sub');else u.searchParams.set('sub',sub);history.replaceState({},'',u)}
function renderFilters(all){document.getElementById('mainFilters').innerHTML=mainOrder.map(k=>`<button class="pill ${active===k?'is-active':''}" data-main="${k}" style="background:${active===k?'#f5f5f2':'transparent'};color:${active===k?'#0a0a0a':'inherit'};cursor:pointer">${labels[k]}</button>`).join('');const cfg=categories[active];document.getElementById('subFilters').innerHTML=cfg?.subs?cfg.subs.map(k=>`<button class="pill" data-sub="${k}" style="background:${sub===k?'#f5f5f2':'transparent'};color:${sub===k?'#0a0a0a':'inherit'};cursor:pointer">${labels[k]}</button>`).join(''):'';document.getElementById('pageTitle').textContent=cfg?.title||'All Works';document.getElementById('pageIntro').textContent=cfg?.intro||'';document.querySelectorAll('[data-main]').forEach(b=>b.onclick=()=>{active=b.dataset.main;sub='all';updateURL();render(all)});document.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>{sub=b.dataset.sub;updateURL();render(all)})}
function card(p,i){const visual=p.image_url?`<div class="visual"><img src="${p.image_url}" alt="${p.title}" loading="lazy" onerror="this.parentElement.classList.add('gradient-1');this.remove()"></div>`:`<div class="visual gradient-1"><div class="ghost">${p.title}</div></div>`;const href=p.category_key?`collection.html?id=${encodeURIComponent(p.id)}`:`project.html?project=${encodeURIComponent(p.slug||p.id)}`;return `<a class="card ${i===0?'big':i===1?'med':'small'}" data-cursor="OPEN" href="${href}">${visual}<div class="meta"><div class="kicker">${p.category||'Project'}</div><div class="meta-head"><h3>${p.title}</h3><span class="arrow">↗</span></div><p>${p.description||''}</p></div></a>`}
function render(all){renderFilters(all);let items=active==='all'?all:all.filter(p=>keyFor(p)===active);if(sub!=='all')items=items.filter(p=>subKeyFor(p)===sub);const grid=document.getElementById('archiveGrid');grid.innerHTML=items.map(card).join('');document.getElementById('emptyState').style.display=items.length?'none':'flex';document.querySelectorAll('.reveal').forEach(el=>el.classList.add('show'))}
Promise.all([
 fetch('./projects.json',{cache:'no-store'}).then(r=>r.ok?r.json():[]).catch(()=>[]),
 fetch('./archive-data.json',{cache:'no-store'}).then(r=>r.ok?r.json():[]).catch(()=>[])
]).then(([projects,archive])=>render([...(Array.isArray(projects)?projects:[]),...(Array.isArray(archive)?archive:[])]));